In [2]:
import numpy as np

In [3]:
# 3 vectors to test the alogirthm with
x1 = [1,4,6,5,4,7,8,9,0,5,4,3,2,4,5,-4,-9]
x2 = [2,3,6,5,5,7,9,10,0,5,4,2,2,5,7,-3,-10]
x3 = [1,3,5,7,2,7,10,4,1,5,5,4,2,3,4,-6,-7]
y = [2,4,5,5,4,8,10,8,0,5,3,4,2,5,6,-5,-8]

In [4]:
def linear_model(y,*args):
    #Multiple linear regression function which takes input of 1 response variable and multiple explanatory variables.
    
    X = np.array([np.ones(len(y))]).T     # Create vertical vector of 1's.
    Y = np.array([y]).T     # Create a vertical vector of the response variable input - y.
    
    for x in args:
        x1 = np.array([x]).T
        X = np.concatenate((X,x1),axis=1)      # This loop concantenates the input explanatory vectors to vector X above.
    
    XX = np.linalg.inv(X.T.dot(X))     # Inverse of the dot product the new vector X with its transpose.
    Xy = X.T.dot(Y)     # Dot product the new vector X with the response variable Y
    
    B = XX.dot(Xy)      # Dot product of the maticies XX and Xy returns the  regression coeffiecnts of the model.
    print('Coefficients', B)
    
    y_hat = X.dot(B)     # Returns the fitted values of the model.
    print('Fitted Values', y_hat)
    
    r = Y - y_hat       # Returns the residuals from the model.
    print('Redisuals', r)
    
    RSS = Y.T.dot(Y) - (B.T.dot(X.T)).dot(Y)
    Sr_squared = RSS/(len(Y)-len(args)-1)     # Gives the value of the Residual Standard error squared.
    print('Residual Standard error squared', Sr_squared)
    
    TSS = Y.T.dot(Y)-len(Y)*np.mean(Y)**2
    R_squared = 1 - RSS/TSS      # Gives the value of R squared.
    print('R Squared' , R_squared)
    
    adj_R_squared = 1 - (RSS/(len(Y)-len(args)-1))/(TSS/(len(Y)-1))    # Gives the adjusted R squared value.
    print('Adjusted R Squared', adj_R_squared)
    
    varB = Sr_squared*np.linalg.inv(X.T.dot(X))     # Returns the covariance matrix of the model.
    print('Covariance matrix', varB)
    
    t_matrix = np.empty(0)    # Create an empty matrix
    
    for i in range(len(varB)):
        SE = np.sqrt(varB[i][i])    # Loop each value in the diagonal of the covariance matrix.
        t = B[i]/SE      # Divide each iteration of the vector B by the value SE.
        t_matrix = np.append(t_matrix,t)   # Create a vector with all of these values.
    print('t values', t_matrix)   # Returns the t values of the model to see if each variable is significant.

In [6]:
linear_model(y,x1,x2,x3)

Coefficients [[0.15552455]
 [0.30576907]
 [0.36761528]
 [0.34310502]]
Fitted Values [[ 1.53962921]
 [ 3.51076175]
 [ 5.91135579]
 [ 5.92418147]
 [ 3.9028873 ]
 [ 7.27095018]
 [ 9.34126489]
 [ 7.95601912]
 [ 0.49862957]
 [ 5.23797143]
 [ 4.56458707]
 [ 3.18048241]
 [ 2.1885033 ]
 [ 4.24599232]
 [ 5.63009698]
 [-4.22902771]
 [-8.67428508]]
Redisuals [[ 0.46037079]
 [ 0.48923825]
 [-0.91135579]
 [-0.92418147]
 [ 0.0971127 ]
 [ 0.72904982]
 [ 0.65873511]
 [ 0.04398088]
 [-0.49862957]
 [-0.23797143]
 [-1.56458707]
 [ 0.81951759]
 [-0.1885033 ]
 [ 0.75400768]
 [ 0.36990302]
 [-0.77097229]
 [ 0.67428508]]
Residual Standard error squared [[0.64057988]]
R Squared [[0.97398601]]
Adjusted R Squared [[0.96798278]]
Covariance matrix [[ 0.0601822   0.00686928 -0.00964566 -0.00368729]
 [ 0.00686928  0.12092871 -0.08849116 -0.02851899]
 [-0.00964566 -0.08849116  0.07237681  0.01344534]
 [-0.00368729 -0.02851899  0.01344534  0.01618868]]
t values [0.63396446 0.87928335 1.36645028 2.69662956]
